name: Beta Release Workflow

on:
  push:
    branches:
      - master

jobs:
  beta-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name bhoos-devops
          git config user.email devops@bhoos.com

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bhoos'

      # Install packages with PERSONAL_ACCESS_TOKEN since it might
      # need access to other repos
      - name: Install Packages
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Publish with GITHUB_TOKEN, since this also requies pushing
      # to the repository and we don't want to trigger another
      # action run, which happens when PERSONAL_ACCESS_TOKEN is used
      - name: Publish Beta
        run: |
          yarn build
          yarn version --prerelease --preid beta
          yarn publish --tag beta
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
