name: Beta Release Workflow

on:
  push:
    branches:
      - master

jobs:
  beta-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name bhoos-devops
          git config user.email devops@bhoos.com

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bhoos'

      # Install packages with PERSONAL_ACCESS_TOKEN since it might
      # need access to other repos
      - name: Install Packages
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Publish with GITHUB_TOKEN, since this also requies pushing
      # to the repository and we don't want to trigger another
      # action run, which happens when PERSONAL_ACCESS_TOKEN is used
      - name: Publish Beta
        run: |
          yarn build
          yarn version --prerelease --preid beta
          yarn publish --tag beta
          git push
          echo "RELEASE_TAG=$(git describe --tags)" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Generate PR for release
        if: endsWith(${{ env.RELEASE_TAG }}, '-beta.0')
        run: |
          release=${RELEASE_TAG:0:}
          gh pr create --title "Release ${RELEASE_TAG:0:${#RELEASE_TAG}-6}" --body "" --base release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

